//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAM.Brilliance.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JAM.Brilliance.App_GlobalResources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anna.
        /// </summary>
        public static string About_Anna {
            get {
                return ResourceManager.GetString("About_Anna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charlotte (Köpenhamn/Öresundsregionen).
        /// </summary>
        public static string About_Charlotte {
            get {
                return ResourceManager.GetString("About_Charlotte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förutom att arbeta som matchmaker är jag är receptionschef på ett av de största hotellen i Köpenhamn och möter till vardags väldigt många människor. Under mina 13 år i servicebranschen har jag lärt mig läsa av människor och har fått en människokännedom som jag nu har stor nytta av. Jag har ett 12 år långt förhållande bakom mig och vet att det är en utmaning att hitta en person som man verkligen känner den där fina kontakten med och viktigast av allt att få dela glädje o sorg med. Jag vill genom matchmaking  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_Charlotte_More {
            get {
                return ResourceManager.GetString("About_Charlotte_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emelie (Öresundsregionen).
        /// </summary>
        public static string About_Emelie {
            get {
                return ResourceManager.GetString("About_Emelie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förutom att arbeta som personlig matchmaker är jag specialistutbildad sjuksköterska. Jag studerar även på halvfart vid Lunds Universitet. På min fritid tränar jag eller gör andra sociala aktiviteter. Jag kommer således i kontakt med otroligt mycket människor i min vardag och har genom åren utvecklat en god människokännedom. Alla människor är olika och värdesätter olika när det kommer till kärlek. Med tanke på att en relation förhoppningsvis är livslång tycker jag inte att man ska behöva nöja sig med något s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_Emelie_More {
            get {
                return ResourceManager.GetString("About_Emelie_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Med vår samlade kunskap och erfarenhet ser vi fram emot att hjälpa dig hitta din partner. Varmt välkommen att höra av dig!.
        /// </summary>
        public static string About_Footer {
            get {
                return ResourceManager.GetString("About_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeanette.
        /// </summary>
        public static string About_Jeanette {
            get {
                return ResourceManager.GetString("About_Jeanette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jag är utbildad kostrådgivare, personlig tränare och massageterapeut och driver eget företag inom friskvård sedan 8 år tillbaka. Jag har ett 10-årigt samboskap bakom mig och två barn. Efter ett par års erfarenhet av dejtingsidor kände jag att det saknades en personlig matchingmakingservice. Därför är jag glad att vi nu kan erbjuda dig detta!.
        /// </summary>
        public static string About_Jeanette_More {
            get {
                return ResourceManager.GetString("About_Jeanette_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linda (Köpenhamn/Öresundsregionen).
        /// </summary>
        public static string About_Linda {
            get {
                return ResourceManager.GetString("About_Linda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förutom att arbeta som matchmaker så jobbar jag som vägledande konsult inom företaget själens kraft. Jag håller kurser, arbetar med kost, näringslära, yoga, qigong &amp; meditation. Jag har lång erfarenhet av att hjälpa människor att se möjligheter när de står vid vägskäl. Kärlek i livet är något av det viktigaste som finns och med mina kunskaper ser jag fram emot att finna kärleken till dig..
        /// </summary>
        public static string About_Linda_More {
            get {
                return ResourceManager.GetString("About_Linda_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nina (Öresundsregionen).
        /// </summary>
        public static string About_Nina {
            get {
                return ResourceManager.GetString("About_Nina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jag är utbildad Civilekonom och arbetar idag som konsultchef med försäljning och rekrytering på världens näst största HR-service företag. Förutom mitt arbete som representant för J&amp;A Matchmaking spenderar jag mina dagar med att nätverka, genomföra kundbesök och hålla intervjuer. Mitt arbete kräver stor människokännedom och ett stort kontaktnät, lyckligtvis besitter jag båda delar och hoppas få dela med mig av detta när jag ska hjälpa dig hitta din kärlekspartner. Jag har flera långa förhållanden bakom mig o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_Nina_More {
            get {
                return ResourceManager.GetString("About_Nina_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nisse (Öresundsregionen).
        /// </summary>
        public static string About_Nisse {
            get {
                return ResourceManager.GetString("About_Nisse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Äntligen kan jag ägna mig åt att arbeta med det bästa som finns, kärleken! Förutom mitt arbete som representant för J&amp;A Matchmaking så finns jag i försäljningsbranschen och där har jag 18 års erfarenhet på olika nivåer. Jag har stor social kompetens och människokännedom som jag hoppas få användning för i min strävan att hjälpa dig hitta kärleken. Jag är än så länge singel själv och vet hur det är att ha höga krav och hur svårt det är att hitta den som känns mitt i prick..
        /// </summary>
        public static string About_Nisse_More {
            get {
                return ResourceManager.GetString("About_Nisse_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2011 startade J&amp;A Matchmaking som en följd av att matchmaking saknades i Sverige. Vår erfarenhet är att både matchmaking och onlinedating har en funktion att fylla. Eftersom vi vill att alla ska få möjligheten att hitta kärleken så väljer vi att erbjuda både onlinedating och matchmaking. För den som behöver ytterligare stöd i form av tex coaching eller hjälp att vässa din onlineprofil så har vi även dessa tjänster att erbjuda.  Vår onlinedatingsida är det enda  sidan där du kan bli headhuntad av en personli [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_Us {
            get {
                return ResourceManager.GetString("About_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ylva (Stockholmsregionen).
        /// </summary>
        public static string About_Ylva {
            get {
                return ResourceManager.GetString("About_Ylva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jag är utbildad Public Bid Manager och har jobbat med försäljning mot sjukvården under flera år. Förutom att arbeta med matchmaking driver idag en egen webshop med exklusivare inredningsdetaljer, utvalda med fingertoppskänsla. Jag har ett 20-årigt äktenskap bakom mig och njuter nu frukterna av detta, en son och en dotter. Som singel har även jag erfarenhet av dejting och har en del råd och tips att ge kring detta. Min stora hobby förutom inredning är beteendevetenskap där jag läser så mycket jag kommer över [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_Ylva_More {
            get {
                return ResourceManager.GetString("About_Ylva_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du ha peppning och nya idéer? Det kan vara krävande att vara singel, det vet vi som arbetar med singlar. Det gäller att alltid framställa sig själv från sin bästa sida och vara på topp. Vi hjälper dig!.
        /// </summary>
        public static string Coaching_P1 {
            get {
                return ResourceManager.GetString("Coaching_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samtalen sköts enl ök inom 12 v, du kan tex använda dig av samtalen inför en dejt eller efter en dejt eller övrig dejtcoaching..
        /// </summary>
        public static string Coaching_P10 {
            get {
                return ResourceManager.GetString("Coaching_P10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det är svårt att hitta rätt partner, det vet säkert du också. Dessutom har du kanske inrättat ett ganska bekvämt singelliv utifrån sina egna premisser och är inte alltid så sugen att förändra detta. Är det kanske så att du ibland blir hindrad av dina egna krav och har du tänkt tanken att titta utanför boxen?.
        /// </summary>
        public static string Coaching_P2 {
            get {
                return ResourceManager.GetString("Coaching_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ibland kan det underlätta att bolla dessa tankar med någon utomstående som vet vad det innebär. Vi som pratar med singelmän och singelkvinnor dagligen kan hjälpa dig att reda ut begreppen. Vi kan stärka dig och ge dig konkreta tips på vad som kan vara bra att tänka på när du flirtar och dejtar..
        /// </summary>
        public static string Coaching_P3 {
            get {
                return ResourceManager.GetString("Coaching_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dejtcoaching via telefon:.
        /// </summary>
        public static string Coaching_P4 {
            get {
                return ResourceManager.GetString("Coaching_P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 min: 499:-.
        /// </summary>
        public static string Coaching_P5 {
            get {
                return ResourceManager.GetString("Coaching_P5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 min: 799:-.
        /// </summary>
        public static string Coaching_P6 {
            get {
                return ResourceManager.GetString("Coaching_P6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coachingpaket 3 x 30 min 1350:-.
        /// </summary>
        public static string Coaching_P7 {
            get {
                return ResourceManager.GetString("Coaching_P7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samtalen sköts enl ök inom 6 v, du kan tex använda dig av samtalen inför en dejt eller efter en dejt eller övrig dejtcoaching..
        /// </summary>
        public static string Coaching_P8 {
            get {
                return ResourceManager.GetString("Coaching_P8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coachingpaket 6 x 30 min 2500:-.
        /// </summary>
        public static string Coaching_P9 {
            get {
                return ResourceManager.GetString("Coaching_P9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coaching.
        /// </summary>
        public static string Coaching_Title {
            get {
                return ResourceManager.GetString("Coaching_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anna Dingizian, Delägare/Representant Öresundsregionen: +46 (0)733-529 987.
        /// </summary>
        public static string Constants_AnnaInfo {
            get {
                return ResourceManager.GetString("Constants_AnnaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seriöst&amp;nbsp;-&amp;nbsp;personligt&amp;nbsp;-&amp;nbsp;professionellt&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;.
        /// </summary>
        public static string Constants_Banner {
            get {
                return ResourceManager.GetString("Constants_Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charlotte Aldin, Representant Köpenhamn/Öresundsregionen: 0709-328 182.
        /// </summary>
        public static string Constants_CharlotteInfo {
            get {
                return ResourceManager.GetString("Constants_CharlotteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Kontakta oss&lt;/h2&gt;&lt;p&gt;Jeanette Vinberg: +46 (0)702-650 361&lt;br /&gt;Anna Dingizian: +46 (0)733-529 987&lt;br /&gt;Mailadress: &lt;a href=&quot;mailto:jamatchmaking@gmail.com&quot;&gt;jamatchmaking@gmail.com&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string Constants_ContactFooter {
            get {
                return ResourceManager.GetString("Constants_ContactFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Copyright (c) 2014 J&amp;A Matchmaking. All Rights Reserved.&lt;/p&gt;.
        /// </summary>
        public static string Constants_Copyright {
            get {
                return ResourceManager.GetString("Constants_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emelie, Representant Öresundsregionen: 0765-591 604.
        /// </summary>
        public static string Constants_EmelieInfo {
            get {
                return ResourceManager.GetString("Constants_EmelieInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dating.
        /// </summary>
        public static string Constants_Headline {
            get {
                return ResourceManager.GetString("Constants_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeanette Vinberg, Delägare/Representant Öresundsregionen: +46 (0)702-650 361.
        /// </summary>
        public static string Constants_JeanetteInfo {
            get {
                return ResourceManager.GetString("Constants_JeanetteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linda Fennhagen, Representant Köpenhamn/Öresundsregionen: 0736-836 421.
        /// </summary>
        public static string Constants_LindaInfo {
            get {
                return ResourceManager.GetString("Constants_LindaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nina von Platen, Representant Öresundsregionen: 0733-966 337.
        /// </summary>
        public static string Constants_NinaInfo {
            get {
                return ResourceManager.GetString("Constants_NinaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nisse Andersson, Representant Öresundsregionen: 0737-404 013.
        /// </summary>
        public static string Constants_NisseInfo {
            get {
                return ResourceManager.GetString("Constants_NisseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Innehar F-skattsedel&lt;br /&gt;&lt;br /&gt;Denna hemsida använder cookies.&lt;/p&gt;.
        /// </summary>
        public static string Constants_Tax {
            get {
                return ResourceManager.GetString("Constants_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ylva Vezzoli, Representant Stockholmsregionen: 0702-730 022.
        /// </summary>
        public static string Constants_YlvaInfo {
            get {
                return ResourceManager.GetString("Constants_YlvaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemsida.
        /// </summary>
        public static string ContactUs_Homepage {
            get {
                return ResourceManager.GetString("ContactUs_Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailadress.
        /// </summary>
        public static string ContactUs_Mail {
            get {
                return ResourceManager.GetString("ContactUs_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakta Oss.
        /// </summary>
        public static string ContactUs_Title {
            get {
                return ResourceManager.GetString("ContactUs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi gör jobbet åt dig och du kan fokusera på annat. Kanske du inte har tid att nätdejta eller gå på krogen, eller kanske du har en position som gör det mindre lämpligt att exponera sig på nätet. Du som är blyg eller tillbakadragen kan få möjlighet att gå på dejt, du kan även få coaching att våga mer. Du slipper råka ut för någon som marknadsfört sig falskt på nätet..
        /// </summary>
        public static string FAQ_A1 {
            get {
                return ResourceManager.GetString("FAQ_A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nej, alla är välkomna men vi utgår från öresundsregionen och Stockholmsområdet..
        /// </summary>
        public static string FAQ_A2 {
            get {
                return ResourceManager.GetString("FAQ_A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nej, tyvärr inte eftersom vi sätter konfidentialiteten högt..
        /// </summary>
        public static string FAQ_A3 {
            get {
                return ResourceManager.GetString("FAQ_A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nej, vi presenterar kandidaten sen är det upp till dig som medlem att avgöra om du vill träffas..
        /// </summary>
        public static string FAQ_A4 {
            get {
                return ResourceManager.GetString("FAQ_A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja, om båda samtycker..
        /// </summary>
        public static string FAQ_A5 {
            get {
                return ResourceManager.GetString("FAQ_A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maten ingår inte i servicen och om ni hellre vill boka själv går det bra..
        /// </summary>
        public static string FAQ_A6 {
            get {
                return ResourceManager.GetString("FAQ_A6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alla lyckönskningar till dig i så fall! Återköp sker ej men du kan ge bort medlemskapet till någon annan..
        /// </summary>
        public static string FAQ_A7 {
            get {
                return ResourceManager.GetString("FAQ_A7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi vill gärna arbeta även med samkönade relationer i framtiden. Tyvärr har vi inte möjligheten att erbjuda denna service ännu, men håll utkik framöver!.
        /// </summary>
        public static string FAQ_A8 {
            get {
                return ResourceManager.GetString("FAQ_A8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varför ska jag välja personlig matchmaking?.
        /// </summary>
        public static string FAQ_Q1 {
            get {
                return ResourceManager.GetString("FAQ_Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Måste man bo i öresundsregionen eller Stockholm för att få vara medlem?.
        /// </summary>
        public static string FAQ_Q2 {
            get {
                return ResourceManager.GetString("FAQ_Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finns det något öppet forum där man kan prata med andra medlemmar?.
        /// </summary>
        public static string FAQ_Q3 {
            get {
                return ResourceManager.GetString("FAQ_Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Måste jag tacka ja till de dejter ni föreslår?.
        /// </summary>
        public static string FAQ_Q4 {
            get {
                return ResourceManager.GetString("FAQ_Q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finns det möjlighet att få se en bild eller att få pratas vid via telefon innan träff?.
        /// </summary>
        public static string FAQ_Q5 {
            get {
                return ResourceManager.GetString("FAQ_Q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ni uppger att ni kan ordna dejten via restaurang eller café, ingår maten då? Kan man boka själv på valfritt ställe?.
        /// </summary>
        public static string FAQ_Q6 {
            get {
                return ResourceManager.GetString("FAQ_Q6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vad händer om jag träffar min drömpartner efter att jag anmält mig hos er, kan jag få pengarna tillbaka då?.
        /// </summary>
        public static string FAQ_Q7 {
            get {
                return ResourceManager.GetString("FAQ_Q7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbetar ni inte med samkönade relationer?.
        /// </summary>
        public static string FAQ_Q8 {
            get {
                return ResourceManager.GetString("FAQ_Q8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om oss.
        /// </summary>
        public static string Menu_AboutUs {
            get {
                return ResourceManager.GetString("Menu_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coaching.
        /// </summary>
        public static string Menu_Coaching {
            get {
                return ResourceManager.GetString("Menu_Coaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakta oss.
        /// </summary>
        public static string Menu_ContactUs {
            get {
                return ResourceManager.GetString("Menu_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string Menu_Faq {
            get {
                return ResourceManager.GetString("Menu_Faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressrum.
        /// </summary>
        public static string Menu_Press {
            get {
                return ResourceManager.GetString("Menu_Press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priser.
        /// </summary>
        public static string Menu_Prices {
            get {
                return ResourceManager.GetString("Menu_Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processen.
        /// </summary>
        public static string Menu_Process {
            get {
                return ResourceManager.GetString("Menu_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenser.
        /// </summary>
        public static string Menu_References {
            get {
                return ResourceManager.GetString("Menu_References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representanter.
        /// </summary>
        public static string Menu_Reps {
            get {
                return ResourceManager.GetString("Menu_Reps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök.
        /// </summary>
        public static string Menu_Search {
            get {
                return ResourceManager.GetString("Menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vässa profilen.
        /// </summary>
        public static string Menu_Sharpen {
            get {
                return ResourceManager.GetString("Menu_Sharpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmälan.
        /// </summary>
        public static string Menu_Signup {
            get {
                return ResourceManager.GetString("Menu_Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Menu_Start {
            get {
                return ResourceManager.GetString("Menu_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressrum.
        /// </summary>
        public static string Press_Title {
            get {
                return ResourceManager.GetString("Press_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Intervju och profilskiss av dig&lt;/li&gt;
        ///&lt;li&gt;Aktivt sökande av en match för dig&lt;/li&gt;
        ///&lt;li&gt;Administration av ditt ärende&lt;/li&gt;
        ///&lt;li&gt;Sekretess genom alla led&lt;/li&gt;
        ///&lt;li&gt;1 eller flera matchningar presenteras för dig&lt;/li&gt;
        ///&lt;li&gt;Intervju och profilskiss av din dejt/dejter&lt;/li&gt;
        ///&lt;li&gt;Korrespondens med dig angående förslag på dejt&lt;/li&gt;
        ///&lt;li&gt;Bokning av dejt för er&lt;/li&gt;
        ///&lt;li&gt;Uppföljningssamtal efter er dejt&lt;/li&gt;
        ///&lt;li&gt;Coaching inför dejten&lt;/li&gt;
        ///&lt;li&gt;Bakgrundskoll av din dejt via brottsregister&lt;/li&gt;
        ///&lt;li&gt;Allmän dej [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Prices_Base {
            get {
                return ResourceManager.GetString("Prices_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observera att de 9 första punkterna alltid ingår och inte går att välja bort..
        /// </summary>
        public static string Prices_Base_Price {
            get {
                return ResourceManager.GetString("Prices_Base_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string Prices_Base_Title {
            get {
                return ResourceManager.GetString("Prices_Base_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to För dig som vill bli säkrare och tryggare när du är ute och träffar människor eller dejtar erbjuder vi dejtcoahcing. Du får tips och verktyg för hur du kan agera vid nya kontakter med människor. Du får coaching och peptalk för att bli lyft och kunna möta människor med större säkerhet. Ring eller maila oss för att boka en tid.&lt;br/&gt;
        ///Pris: &lt;b&gt;995:-&lt;/b&gt; / 45 min.
        /// </summary>
        public static string Prices_Coaching {
            get {
                return ResourceManager.GetString("Prices_Coaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dejt/relationscoaching.
        /// </summary>
        public static string Prices_Coaching_Title {
            get {
                return ResourceManager.GetString("Prices_Coaching_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varmt välkomna!.
        /// </summary>
        public static string Prices_End {
            get {
                return ResourceManager.GetString("Prices_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string Prices_Gold {
            get {
                return ResourceManager.GetString("Prices_Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string Prices_Gold_Price {
            get {
                return ResourceManager.GetString("Prices_Gold_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string Prices_Gold_Title {
            get {
                return ResourceManager.GetString("Prices_Gold_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alla människor är olika när det gäller synen på och kraven man har vid sökandet efter en partner. Vi har förståelse för detta och kan hjälpa dig med dina specifika krav. Eftersom var och ens situation är unik har vi valt att inte erbjuda färdiga lösningar. Beroende på dina krav och din situation kommer vi överens om en lösning och ett pris som passar just dig..
        /// </summary>
        public static string Prices_Intro {
            get {
                return ResourceManager.GetString("Prices_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Följande finns i vår service:.
        /// </summary>
        public static string Prices_Or {
            get {
                return ResourceManager.GetString("Prices_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betalning sker till bankgiro: 839-2714.
        /// </summary>
        public static string Prices_Payment {
            get {
                return ResourceManager.GetString("Prices_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string Prices_Platinum {
            get {
                return ResourceManager.GetString("Prices_Platinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string Prices_Platinum_Price {
            get {
                return ResourceManager.GetString("Prices_Platinum_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string Prices_Platinum_Title {
            get {
                return ResourceManager.GetString("Prices_Platinum_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string Prices_Renew {
            get {
                return ResourceManager.GetString("Prices_Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priser.
        /// </summary>
        public static string Prices_Title {
            get {
                return ResourceManager.GetString("Prices_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmälan gör du via fliken anmälan..
        /// </summary>
        public static string Process_P1 {
            get {
                return ResourceManager.GetString("Process_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to När vi fått din anmälan så kommer vi kontakta dig inom några dagar för att boka ett personligt möte. Du får även ett kundnummer som du ska ange vid betalningen..
        /// </summary>
        public static string Process_P2 {
            get {
                return ResourceManager.GetString("Process_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi träffas för att närmre gå igenom dina önskemål. Det personliga mötet är basen i verksamheten för att hitta din bästa match..
        /// </summary>
        public static string Process_P3 {
            get {
                return ResourceManager.GetString("Process_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi återkommer när vi hittat en lämplig kandidat för en dejt. Om ni vill se varandras foto före dejt så är det möjligt efter era godkännanden. Vi ombesörjer att boka bord på passande restaurang eller café..
        /// </summary>
        public static string Process_P4 {
            get {
                return ResourceManager.GetString("Process_P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efter dejten kontaktar vi dig för feedback..
        /// </summary>
        public static string Process_P5 {
            get {
                return ResourceManager.GetString("Process_P5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Så här går det till.
        /// </summary>
        public static string Process_Title {
            get {
                return ResourceManager.GetString("Process_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Magnus och Johanna:&lt;/b&gt;.
        /// </summary>
        public static string References_1 {
            get {
                return ResourceManager.GetString("References_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Magnus, 41:&lt;/b&gt; &quot;Jag separerade från min sambo för 2½ år sedan och efter det så har det bara inte blivit av att jag tänkt så mycket på det här med att träffa någon. Det har bara inte blivit prioritet även om jag känt att jag verkligen inte vill leva som singel för alltid, alltså jag vill ju ha barn och så... Jag har ju varit ute med grabbarna en hel del men det är inte riktigt min grej att flirta, helt ärligt kommer jag nog inte ihåg hur man gör för det var så länge sedan jag var singel, det var före jag [rest of string was truncated]&quot;;.
        /// </summary>
        public static string References_2 {
            get {
                return ResourceManager.GetString("References_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Johanna, 37:&lt;/b&gt; &quot;Jag har varit singel i 5 år innan jag träffade Magnus. Det har varit en hel del dejtande under dessa åren! Tyvärr är det väldigt svårt att hitta den rätte där ute... Att ragga på krogen kan funka ibland men oftast är det väldigt jobbigt, folk är fulla och dryga. Sedan har jag nätdejtat en hel del också men det är hur svårt som helst att hitta guldkornen bland alla möjliga konstiga. Tyvärr är det allt för många som presenterar en oäkta bild av sig själva på nätet, till slut tröttnar man  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string References_3 {
            get {
                return ResourceManager.GetString("References_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;P-O och Louise:&lt;/b&gt;.
        /// </summary>
        public static string References_4 {
            get {
                return ResourceManager.GetString("References_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;P-O, 55:&lt;/b&gt; &quot;Efter min skilsmässa 2002 så har jag dels haft ett längre särboskap men även bott utomlands längre perioder. Eftersom jag bott utomlands har jag inte haft så etablerat nätverk här i Sverige. Jag tycker det har varit befriande att vara singel under längre perioder efter att ha varit gift och haft familj och hela den biten tidigare. Fast jag tror inte någon tycker det är kul att vara singel när man är 70 år. Jag ville hitta någon som motsvarade mina krav på en partner, någon som tycker om att [rest of string was truncated]&quot;;.
        /// </summary>
        public static string References_5 {
            get {
                return ResourceManager.GetString("References_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Louise, 55:&lt;/b&gt; &quot;Min exman gick bort i sjukdom 2007, det var en tung tid för mig efteråt. Våra barn är vuxna och studerar utomlands så jag måste erkänna att jag känt mig väldigt ensam. Jag har haft en stark längtan länge efter att träffa någon ny partner att dela tillvaron med, men det är så svårt i min ålder att hitta någon. Jag har inte för vana att gå på krogen precis och i mitt nätverk är de flesta redan i relationer. Jag fick kontakt med J&amp;A Matchmaking via en mässa och tvekade ett bra tag innan jag [rest of string was truncated]&quot;;.
        /// </summary>
        public static string References_6 {
            get {
                return ResourceManager.GetString("References_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenser.
        /// </summary>
        public static string References_Title {
            get {
                return ResourceManager.GetString("References_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avancerad sökning.
        /// </summary>
        public static string Search_Adv {
            get {
                return ResourceManager.GetString("Search_Adv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to och.
        /// </summary>
        public static string Search_And {
            get {
                return ResourceManager.GetString("Search_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök en passande match för dig i vårt exklusiva register. Välj mellan .
        /// </summary>
        public static string Search_P1 {
            get {
                return ResourceManager.GetString("Search_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snabbsökning.
        /// </summary>
        public static string Search_Quick {
            get {
                return ResourceManager.GetString("Search_Quick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök.
        /// </summary>
        public static string Search_Title {
            get {
                return ResourceManager.GetString("Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Många kunder hör av sig till oss med funderingar kring hur man presenterar sig på bästa sätt när man söker matcher online. Många känner att det är svårt att framhäva sig själv, hur gör man för att det inte ska bli för skrytsamt eller för blygsamt? Det är avgörande hur man formulerar sig i sin presentation, de ord du väljer påverkar läsaren. Det är också viktigt att ge en så sann bild av dig själv som möjligt för att öka chanserna att träffa någon som verkligen matchar. Likaså är det avgörande vilka bilder d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Sharpen_P1 {
            get {
                return ResourceManager.GetString("Sharpen_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detta kan vi hjälpa dig med:&lt;ul&gt;
        ///&lt;li&gt;Att välja den profilbild som framhäver dig på bästa sätt.&lt;/li&gt;
        ///&lt;li&gt;Att välja bra bilder av dig till ditt album.&lt;/li&gt;
        ///&lt;li&gt;Vi hjälper dig formulera din presentation så den blir tilltalande och framhäver dig på bästa sätt.&lt;/li&gt;
        ///&lt;li&gt;Vi kan hjälpa dig formulera din text så att du uppmärksammas av den sortens match som du söker.&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        public static string Sharpen_P2 {
            get {
                return ResourceManager.GetString("Sharpen_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisförslag: 450:-.
        /// </summary>
        public static string Sharpen_P3 {
            get {
                return ResourceManager.GetString("Sharpen_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vässa Profilen.
        /// </summary>
        public static string Sharpen_Title {
            get {
                return ResourceManager.GetString("Sharpen_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välkommen till Sveriges första online datingsida där just du kan bli headhuntad av personliga matchmakers..
        /// </summary>
        public static string Start_P2 {
            get {
                return ResourceManager.GetString("Start_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detta är datingsiten som drivs av professionella matchmakers som kan hjälpa dig med allt från datingtips, coaching till hur du presenterar dig själv på bästa sätt online. När du registrerat dig hos oss finns möjligheten att vi kontaktar dig för att du matchar en av våra kunder som anlitat oss som personliga matchmakers på .
        /// </summary>
        public static string Start_P3 {
            get {
                return ResourceManager.GetString("Start_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J&amp;A Matchmaking.
        /// </summary>
        public static string Start_P4 {
            get {
                return ResourceManager.GetString("Start_P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string Start_P5 {
            get {
                return ResourceManager.GetString("Start_P5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrera dig här.
        /// </summary>
        public static string Start_P6 {
            get {
                return ResourceManager.GetString("Start_P6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string Start_P7 {
            get {
                return ResourceManager.GetString("Start_P7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du singel?.
        /// </summary>
        public static string Start_Title {
            get {
                return ResourceManager.GetString("Start_Title", resourceCulture);
            }
        }
    }
}
