//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAM.Brilliance.App_GlobalResources.Survey {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SurveyTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SurveyTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JAM.Brilliance.App_GlobalResources.Survey.SurveyTexts", typeof(SurveyTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Födelsedatum (åååå-mm-dd).
        /// </summary>
        public static string Signup_Birthday {
            get {
                return ResourceManager.GetString("Signup_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stad.
        /// </summary>
        public static string Signup_City {
            get {
                return ResourceManager.GetString("Signup_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmälan är bindande, dock kan du ge bort medlemskap eller frysa det..
        /// </summary>
        public static string Signup_Commitment {
            get {
                return ResourceManager.GetString("Signup_Commitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        public static string Signup_Country {
            get {
                return ResourceManager.GetString("Signup_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Post (konfidentiellt).
        /// </summary>
        public static string Signup_Email {
            get {
                return ResourceManager.GetString("Signup_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Signup_Infp {
            get {
                return ResourceManager.GetString("Signup_Infp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namn.
        /// </summary>
        public static string Signup_Name {
            get {
                return ResourceManager.GetString("Signup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Signup_Phone {
            get {
                return ResourceManager.GetString("Signup_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild.
        /// </summary>
        public static string Signup_Picture {
            get {
                return ResourceManager.GetString("Signup_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postnummer.
        /// </summary>
        public static string Signup_PostalCode {
            get {
                return ResourceManager.GetString("Signup_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kön: Man.
        /// </summary>
        public static string Signup_Sex {
            get {
                return ResourceManager.GetString("Signup_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvinna.
        /// </summary>
        public static string Signup_Sex2 {
            get {
                return ResourceManager.GetString("Signup_Sex2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gatuadress.
        /// </summary>
        public static string Signup_Street {
            get {
                return ResourceManager.GetString("Signup_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användaruppgifter.
        /// </summary>
        public static string Signup_Title {
            get {
                return ResourceManager.GetString("Signup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladda upp en bild på dig själv (jpeg eller png).
        /// </summary>
        public static string Signup_Upload {
            get {
                return ResourceManager.GetString("Signup_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genom att ladda upp en bild godkänner du att den visas för andra efter att den blivit godkänd..
        /// </summary>
        public static string Signup_UploadAgreement {
            get {
                return ResourceManager.GetString("Signup_UploadAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrollera dina svar innan du trycker på knappen.
        /// </summary>
        public static string Signup_Verify {
            get {
                return ResourceManager.GetString("Signup_Verify", resourceCulture);
            }
        }
    }
}
