/*
CREATE TABLE dbo.Surveys 
(
    SurveyId                    INT            IDENTITY (10, 1) NOT NULL PRIMARY KEY,
    IsDisabled                  BIT            NOT NULL DEFAULT 0,
    IsInterviewed               BIT            NOT NULL DEFAULT 0,
    IsPaid                      BIT            NOT NULL DEFAULT 0,
    Name                        NVARCHAR (150) NOT NULL,
    Street                      NVARCHAR (150) NULL,
    PostalCode                  NVARCHAR (15)  NULL,
    City                        NVARCHAR (150) NOT NULL,
    Country                     NVARCHAR (150) NULL,
    Email                       NVARCHAR (150) NOT NULL,
    Phone                       NVARCHAR (150) NULL,
    --IsMale                      BIT            NOT NULL,
    --IsSearchingForMale          BIT            NOT NULL,
    Height                      INT            NOT NULL,
    Weight                      INT            NOT NULL,
    Birth                       DATETIME       NOT NULL,
    MotherLanguage              NVARCHAR (150) NULL,
    Note1                       NVARCHAR (2000) NULL,
    Note2                       NVARCHAR (2000) NULL,
    
    WantedSurveyId				INT            NULL,

    DatePackageId               INT            NOT NULL,
    ReferrerId                  INT            NOT NULL,
    KidsCountId                 INT            NOT NULL,
    KidsWantedCountId           INT            NOT NULL,
    WantedKidsWantedCountId     INT            NOT NULL,
    WhatSearchingForWhatId      INT            NOT NULL DEFAULT (0),
    OriginId                    INT            NOT NULL DEFAULT (2),

    IsSingle                    BIT            NOT NULL DEFAULT 0,
    IsSeparated                 BIT            NOT NULL DEFAULT 0,
    IsDivorced                  BIT            NOT NULL DEFAULT 0,
    IsWidowed                   BIT            NOT NULL DEFAULT 0,
    LivingAloneWithVisitors     BIT            NOT NULL DEFAULT 0,
    LivingAlone                 BIT            NOT NULL DEFAULT 0,
    LivingWithPets              BIT            NOT NULL DEFAULT 0,
    LivingWithKids              BIT            NOT NULL DEFAULT 0,
    LivingWithParents           BIT            NOT NULL DEFAULT 0,
    LivingWithFriends           BIT            NOT NULL DEFAULT 0,
    LivingWithPartTimeKids      BIT            NOT NULL DEFAULT 0,
    IsEthnicNorthEuropean       BIT            NOT NULL DEFAULT 0,
    IsEthnicLatin               BIT            NOT NULL DEFAULT 0,
    IsEthnicMulat               BIT            NOT NULL DEFAULT 0,
    IsEthnicDark                BIT            NOT NULL DEFAULT 0,
    IsEthnicAsian               BIT            NOT NULL DEFAULT 0,
    IsEthnicCaucasic            BIT            NOT NULL DEFAULT 0,
    IsEthnicMiddleEastern       BIT            NOT NULL DEFAULT 0,
    IsRelAdventist              BIT            NOT NULL DEFAULT 0,
    IsRelAgnostic               BIT            NOT NULL DEFAULT 0,
    IsRelSpiritual              BIT            NOT NULL DEFAULT 0,
    IsRelAnglican               BIT            NOT NULL DEFAULT 0,
    IsRelAtheist                BIT            NOT NULL DEFAULT 0,
    IsRelBaptist                BIT            NOT NULL DEFAULT 0,
    IsRelHindu                  BIT            NOT NULL DEFAULT 0,
    IsRelBuddhist               BIT            NOT NULL DEFAULT 0,
    IsRelJewish                 BIT            NOT NULL DEFAULT 0,
    IsRelCatholic               BIT            NOT NULL DEFAULT 0,
    IsRelChistian               BIT            NOT NULL DEFAULT 0,
    IsRelMethodist              BIT            NOT NULL DEFAULT 0,
    IsRelMormon                 BIT            NOT NULL DEFAULT 0,
    IsRelMuslim                 BIT            NOT NULL DEFAULT 0,
    IsRelOrtodox                BIT            NOT NULL DEFAULT 0,
    IsRelPingst                 BIT            NOT NULL DEFAULT 0,
    IsRelProtestant             BIT            NOT NULL DEFAULT 0,
    IsRelTao                    BIT            NOT NULL DEFAULT 0,
    IsRelOther                  BIT            NOT NULL DEFAULT 0,
    IsRelPracticing             BIT            NOT NULL DEFAULT 0, 
    IsRelSomewhat               BIT            NOT NULL DEFAULT 0,
    IsRelNotPracticing          BIT            NOT NULL DEFAULT 0,
    IsProfNot                   BIT            NOT NULL DEFAULT 0,
    IsProfAdmin                 BIT            NOT NULL DEFAULT 0,
    IsProfArtist                BIT            NOT NULL DEFAULT 0,
    IsProfConstruction          BIT            NOT NULL DEFAULT 0,
    IsProfHr                    BIT            NOT NULL DEFAULT 0,
    IsProfIt                    BIT            NOT NULL DEFAULT 0,
    IsProfDetail                BIT            NOT NULL DEFAULT 0,
    IsProfSelf                  BIT            NOT NULL DEFAULT 0,
    IsProfFinance               BIT            NOT NULL DEFAULT 0,
    IsProfSales                 BIT            NOT NULL DEFAULT 0,
    IsProfHealth                BIT            NOT NULL DEFAULT 0,
    IsProfHotel                 BIT            NOT NULL DEFAULT 0,
    IsProfLaw                   BIT            NOT NULL DEFAULT 0,
    IsProfAdvertising           BIT            NOT NULL DEFAULT 0,
    IsProfState                 BIT            NOT NULL DEFAULT 0,
    IsProfEducation             BIT            NOT NULL DEFAULT 0,
    IsProfRetired               BIT            NOT NULL DEFAULT 0,
    IsProfStudent               BIT            NOT NULL DEFAULT 0,
    IsEduBasic                  BIT            NOT NULL DEFAULT 0,
    IsEduCollage                BIT            NOT NULL DEFAULT 0,
    IsEduUniversity             BIT            NOT NULL DEFAULT 0,
    IsEduKand                   BIT            NOT NULL DEFAULT 0,
    IsEduMag                    BIT            NOT NULL DEFAULT 0,
    IsEduDoc                    BIT            NOT NULL DEFAULT 0,
    IsEduLife                   BIT            NOT NULL DEFAULT 0,
    IsIncomeLess                BIT            NOT NULL DEFAULT 0,
    IsIncome1                   BIT            NOT NULL DEFAULT 0,
    IsIncome2                   BIT            NOT NULL DEFAULT 0,
    IsIncome3                   BIT            NOT NULL DEFAULT 0,
    IsIncome4                   BIT            NOT NULL DEFAULT 0,
    IsIncome5                   BIT            NOT NULL DEFAULT 0,
    IsIncomeMore                BIT            NOT NULL DEFAULT 0,
    IsTobacQuitting             BIT            NOT NULL DEFAULT 0,
    IsTobacCigar                BIT            NOT NULL DEFAULT 0,
    IsTobacRegularly            BIT            NOT NULL DEFAULT 0,
    IsTobacParty                BIT            NOT NULL DEFAULT 0,
    IsTobacSnus                 BIT            NOT NULL DEFAULT 0,
    IsTobacNot                  BIT            NOT NULL DEFAULT 0,
    IsAlcNot                    BIT            NOT NULL DEFAULT 0,
    IsAlcLittle                 BIT            NOT NULL DEFAULT 0,
    IsAlcSocially               BIT            NOT NULL DEFAULT 0,
    IsAlcMuch                   BIT            NOT NULL DEFAULT 0,
    IsBodySlim                  BIT            NOT NULL DEFAULT 0,
    IsBodyAverage               BIT            NOT NULL DEFAULT 0,
    IsBodyAthletic              BIT            NOT NULL DEFAULT 0,
    IsBodyHeavy                 BIT            NOT NULL DEFAULT 0,
    IsBodyChubby                BIT            NOT NULL DEFAULT 0,
    IsHairBlond                 BIT            NOT NULL DEFAULT 0,
    IsHairRed                   BIT            NOT NULL DEFAULT 0,
    IsHairBrown                 BIT            NOT NULL DEFAULT 0,
    IsHairGrey                  BIT            NOT NULL DEFAULT 0,
    IsHairBlack                 BIT            NOT NULL DEFAULT 0,
    IsHairBald                  BIT            NOT NULL DEFAULT 0,
    IsHairLengthShaved          BIT            NOT NULL DEFAULT 0,
    IsHairLengthVeryShort       BIT            NOT NULL DEFAULT 0,
    IsHairLengthShort           BIT            NOT NULL DEFAULT 0,
    IsHairLengthShoulder        BIT            NOT NULL DEFAULT 0,
    IsHairLengthLong            BIT            NOT NULL DEFAULT 0,
    IsHairLengthVeryLong        BIT            NOT NULL DEFAULT 0,
    IsEyesBlue                  BIT            NOT NULL DEFAULT 0,
    IsEyesBrown                 BIT            NOT NULL DEFAULT 0,
    IsEyesGrey                  BIT            NOT NULL DEFAULT 0,
    IsEyesGreen                 BIT            NOT NULL DEFAULT 0,
    IsEyesMix                   BIT            NOT NULL DEFAULT 0,
    IsPleWiChest                BIT            NOT NULL DEFAULT 0,
    IsPleWiArms                 BIT            NOT NULL DEFAULT 0,
    IsPleWiLegs                 BIT            NOT NULL DEFAULT 0,
    IsPleWiFeet                 BIT            NOT NULL DEFAULT 0,
    IsPleWiNeck                 BIT            NOT NULL DEFAULT 0,
    IsPleWiHands                BIT            NOT NULL DEFAULT 0,
    IsPleWiHair                 BIT            NOT NULL DEFAULT 0,
    IsPleWiSmile                BIT            NOT NULL DEFAULT 0,
    IsPleWiLips                 BIT            NOT NULL DEFAULT 0,
    IsPleWiMuscles              BIT            NOT NULL DEFAULT 0,
    IsPleWiBelly                BIT            NOT NULL DEFAULT 0,
    IsPleWiEars                 BIT            NOT NULL DEFAULT 0,
    IsPleWiEyes                 BIT            NOT NULL DEFAULT 0,
    IsPleWiButt                 BIT            NOT NULL DEFAULT 0,
    IsPleWiCalf                 BIT            NOT NULL DEFAULT 0,
    IsDressBoheme               BIT            NOT NULL DEFAULT 0,
    IsDressBusiness             BIT            NOT NULL DEFAULT 0,
    IsDressEthnic               BIT            NOT NULL DEFAULT 0,
    IsDressClassic              BIT            NOT NULL DEFAULT 0,
    IsDressFashion              BIT            NOT NULL DEFAULT 0,
    IsDressRock                 BIT            NOT NULL DEFAULT 0,
    IsDressSophisticated        BIT            NOT NULL DEFAULT 0,
    IsDressSport                BIT            NOT NULL DEFAULT 0,
    IsDressTrend                BIT            NOT NULL DEFAULT 0,
    IsBodyArtNever              BIT            NOT NULL DEFAULT 0,
    IsBodyArtVisible            BIT            NOT NULL DEFAULT 0,
    IsBodyArtHidden             BIT            NOT NULL DEFAULT 0,
    IsBodyArtPiercing           BIT            NOT NULL DEFAULT 0,
    IsBodyArtAsk                BIT            NOT NULL DEFAULT 0,
    IsPersonAdventurous         BIT            NOT NULL DEFAULT 0,
    IsPersonCarefree            BIT            NOT NULL DEFAULT 0,
    IsPersonShy                 BIT            NOT NULL DEFAULT 0,
    IsPersonDominant            BIT            NOT NULL DEFAULT 0,
    IsPersonLoner               BIT            NOT NULL DEFAULT 0,
    IsPersonStubborn            BIT            NOT NULL DEFAULT 0,
    IsPersonGenerous            BIT            NOT NULL DEFAULT 0,
    IsPersonHappy               BIT            NOT NULL DEFAULT 0,
    IsPersonHomorous            BIT            NOT NULL DEFAULT 0,
    IsPersonSensitive           BIT            NOT NULL DEFAULT 0,
    IsPersonAmbitious           BIT            NOT NULL DEFAULT 0,
    IsPersonAnalytic            BIT            NOT NULL DEFAULT 0,
    IsPersonTemper              BIT            NOT NULL DEFAULT 0,
    IsPersonLivly               BIT            NOT NULL DEFAULT 0,
    IsPersonCalm                BIT            NOT NULL DEFAULT 0,
    IsPersonRestless            BIT            NOT NULL DEFAULT 0,
    IsPersonConsidering         BIT            NOT NULL DEFAULT 0,
    IsPersonReserved            BIT            NOT NULL DEFAULT 0,
    IsPersonSocial              BIT            NOT NULL DEFAULT 0,
    IsPersonSpantanious         BIT            NOT NULL DEFAULT 0,
    IsPersonCaring              BIT            NOT NULL DEFAULT 0,
    IsPersonInspiring           BIT            NOT NULL DEFAULT 0,
    IsPersonSafe                BIT            NOT NULL DEFAULT 0,
    IsPersonStructured          BIT            NOT NULL DEFAULT 0,
    IsRomanticVery              BIT            NOT NULL DEFAULT 0,
    IsRomantic                  BIT            NOT NULL DEFAULT 0,
    IsRomanticLittle            BIT            NOT NULL DEFAULT 0,
    IsRomanticNot               BIT            NOT NULL DEFAULT 0,
    IsMarriageHoly              BIT            NOT NULL DEFAULT 0,
    IsMarriageVeryImportant     BIT            NOT NULL DEFAULT 0,
    IsMarriageImportant         BIT            NOT NULL DEFAULT 0,
    IsMarriageLessImportant     BIT            NOT NULL DEFAULT 0,
    IsMarriageUnImportant       BIT            NOT NULL DEFAULT 0,
    IsMarriageNotAgain          BIT            NOT NULL DEFAULT 0,
    IsPoliticVeryConservative   BIT            NOT NULL DEFAULT 0,
    IsPoliticConservative       BIT            NOT NULL DEFAULT 0,
    IsPoliticMiddle             BIT            NOT NULL DEFAULT 0,
    IsPoliticLiberal            BIT            NOT NULL DEFAULT 0,
    IsPoliticVeryLiberal        BIT            NOT NULL DEFAULT 0,
    IsPoliticNonConformist      BIT            NOT NULL DEFAULT 0,
    IsPoliticOther              BIT            NOT NULL DEFAULT 0,
    IsMusicNewAge               BIT            NOT NULL DEFAULT 0,
    IsMusicBlues                BIT            NOT NULL DEFAULT 0,
    IsMusicCountry              BIT            NOT NULL DEFAULT 0,
    IsMusicHits                 BIT            NOT NULL DEFAULT 0,
    IsMusicDisco                BIT            NOT NULL DEFAULT 0,
    IsMusicElectronica          BIT            NOT NULL DEFAULT 0,
    IsMusicEthnic               BIT            NOT NULL DEFAULT 0,
    IsMusicFilm                 BIT            NOT NULL DEFAULT 0,
    IsMusicFolk                 BIT            NOT NULL DEFAULT 0,
    IsMusicFunk                 BIT            NOT NULL DEFAULT 0,
    IsMusicGospel               BIT            NOT NULL DEFAULT 0,
    IsMusicMetal                BIT            NOT NULL DEFAULT 0,
    IsMusicHipHop               BIT            NOT NULL DEFAULT 0,
    IsMusicJazz                 BIT            NOT NULL DEFAULT 0,
    IsMusicClassic              BIT            NOT NULL DEFAULT 0,
    IsMusicLatin                BIT            NOT NULL DEFAULT 0,
    IsMusicMusical              BIT            NOT NULL DEFAULT 0,
    IsMusicOpera                BIT            NOT NULL DEFAULT 0,
    IsMusicPop                  BIT            NOT NULL DEFAULT 0,
    IsMusicRnB                  BIT            NOT NULL DEFAULT 0,
    IsMusicRock                 BIT            NOT NULL DEFAULT 0,
    IsMusicReggae               BIT            NOT NULL DEFAULT 0,
    IsMusicSoul                 BIT            NOT NULL DEFAULT 0,
    IsMusicSynth                BIT            NOT NULL DEFAULT 0,
    IsMovieAction               BIT            NOT NULL DEFAULT 0,
    IsMovieAnimation            BIT            NOT NULL DEFAULT 0,
    IsMovieAdventure            BIT            NOT NULL DEFAULT 0,
    IsMovieDocumentary          BIT            NOT NULL DEFAULT 0,
    IsMovieDrama                BIT            NOT NULL DEFAULT 0,
    IsMovieErotic               BIT            NOT NULL DEFAULT 0,
    IsMovieFantasy              BIT            NOT NULL DEFAULT 0,
    IsMovieHistoric             BIT            NOT NULL DEFAULT 0,
    IsMovieIndependent          BIT            NOT NULL DEFAULT 0,
    IsMovieComedy               BIT            NOT NULL DEFAULT 0,
    IsMovieShort                BIT            NOT NULL DEFAULT 0,
    IsMovieWar                  BIT            NOT NULL DEFAULT 0,
    IsMovieCrime                BIT            NOT NULL DEFAULT 0,
    IsMovieManga                BIT            NOT NULL DEFAULT 0,
    IsMovieMusic                BIT            NOT NULL DEFAULT 0,
    IsMovieRomantic             BIT            NOT NULL DEFAULT 0,
    IsMovieThriller             BIT            NOT NULL DEFAULT 0,
    IsMovieSciFi                BIT            NOT NULL DEFAULT 0,
    IsMovieCartoon              BIT            NOT NULL DEFAULT 0,
    IsMovieWestern              BIT            NOT NULL DEFAULT 0,
    IsMovieHorror               BIT            NOT NULL DEFAULT 0,
    IsHobbyNewAge               BIT            NOT NULL DEFAULT 0,
    IsHobbyCars                 BIT            NOT NULL DEFAULT 0,
    IsHobbyDance                BIT            NOT NULL DEFAULT 0,
    IsHobbyAnimals              BIT            NOT NULL DEFAULT 0,
    IsHobbyMovies               BIT            NOT NULL DEFAULT 0,
    IsHobbyHunting              BIT            NOT NULL DEFAULT 0,
    IsHobbyInterior             BIT            NOT NULL DEFAULT 0,
    IsHobbyPhoto                BIT            NOT NULL DEFAULT 0,
    IsHobbyOutdoors             BIT            NOT NULL DEFAULT 0,
    IsHobbyArt                  BIT            NOT NULL DEFAULT 0,
    IsHobbyGame                 BIT            NOT NULL DEFAULT 0,
    IsHobbyCooking              BIT            NOT NULL DEFAULT 0,
    IsHobbyReading              BIT            NOT NULL DEFAULT 0,
    IsHobbyHistory              BIT            NOT NULL DEFAULT 0,
    IsHobbyPainting             BIT            NOT NULL DEFAULT 0,
    IsHobbyMuseum               BIT            NOT NULL DEFAULT 0,
    IsHobbyMusic                BIT            NOT NULL DEFAULT 0,
    IsHobbyPolitics             BIT            NOT NULL DEFAULT 0,
    IsHobbyTravel               BIT            NOT NULL DEFAULT 0,
    IsHobbyRolePlaying          BIT            NOT NULL DEFAULT 0,
    IsHobbyShopping             BIT            NOT NULL DEFAULT 0,
    IsHobbySinging              BIT            NOT NULL DEFAULT 0,
    IsHobbyWriting              BIT            NOT NULL DEFAULT 0,
    IsHobbyGaming               BIT            NOT NULL DEFAULT 0,
    IsHobbyWorkout              BIT            NOT NULL DEFAULT 0,
    IsHobbyDrama                BIT            NOT NULL DEFAULT 0,
    IsHobbyDrawing              BIT            NOT NULL DEFAULT 0,
    IsHobbyGardening            BIT            NOT NULL DEFAULT 0,
    IsHobbyTv                   BIT            NOT NULL DEFAULT 0,
    IsHobbyCircles              BIT            NOT NULL DEFAULT 0,
    IsHobbyHiking               BIT            NOT NULL DEFAULT 0,
    IsHobbyWine                 BIT            NOT NULL DEFAULT 0,
    IsWeekendActive             BIT            NOT NULL DEFAULT 0,
    IsWeekendChill              BIT            NOT NULL DEFAULT 0,
    IsWeekendRandom             BIT            NOT NULL DEFAULT 0,
    IsWeekendPlanned            BIT            NOT NULL DEFAULT 0,
    IsSportDance                BIT            NOT NULL DEFAULT 0,
    IsSportBalls                BIT            NOT NULL DEFAULT 0,
    IsSportMartial              BIT            NOT NULL DEFAULT 0,
    IsSportFitness              BIT            NOT NULL DEFAULT 0,
    IsSportAdventure            BIT            NOT NULL DEFAULT 0,
    IsSportGolf                 BIT            NOT NULL DEFAULT 0,
    IsSportRunning              BIT            NOT NULL DEFAULT 0,
    IsSportRiding               BIT            NOT NULL DEFAULT 0,
    IsSportSailing              BIT            NOT NULL DEFAULT 0,
    IsSportSkating              BIT            NOT NULL DEFAULT 0,
    IsSportSurfing              BIT            NOT NULL DEFAULT 0,
    IsSportYoga                 BIT            NOT NULL DEFAULT 0,
    IsSportRaquet               BIT            NOT NULL DEFAULT 0,
    IsExcerNot                  BIT            NOT NULL DEFAULT 0,
    IsExcerSome                 BIT            NOT NULL DEFAULT 0,
    IsExcerRegular              BIT            NOT NULL DEFAULT 0,
    IsExcerAlways               BIT            NOT NULL DEFAULT 0,
    IsDateBreakfast             BIT            NOT NULL DEFAULT 0,
    IsDateLunch                 BIT            NOT NULL DEFAULT 0,
    IsDateDinner                BIT            NOT NULL DEFAULT 0,
    IsDateMovie                 BIT            NOT NULL DEFAULT 0,
    IsDateBarSnack              BIT            NOT NULL DEFAULT 0,
    IsDateDrinks                BIT            NOT NULL DEFAULT 0,
    IsDatePicnic                BIT            NOT NULL DEFAULT 0,
    IsDateDinnerHome            BIT            NOT NULL DEFAULT 0,
    IsDateFika                  BIT            NOT NULL DEFAULT 0,
    IsLooksImportant            BIT            NOT NULL DEFAULT 0,
    IsLooksLessImportant        BIT            NOT NULL DEFAULT 0,
    IsRelationTogether          BIT            NOT NULL DEFAULT 0,
    IsRelationOwnTime           BIT            NOT NULL DEFAULT 0,
    IsRelationMarriage          BIT            NOT NULL DEFAULT 0,
    IsRelationLiving            BIT            NOT NULL DEFAULT 0,
    IsRelationNotLiving         BIT            NOT NULL DEFAULT 0,
    ChangeDate                  DATETIME       DEFAULT (getdate()) NOT NULL,

    CONSTRAINT FK_Surveys_WantedSurveys_WantedSurveyId FOREIGN KEY (WantedSurveyId) REFERENCES dbo.WantedSurveys (WantedSurveyId),
    --CONSTRAINT FK_Surveys_KidCounts_KidsCountId FOREIGN KEY (KidsCountId) REFERENCES dbo.KidCounts (KidCountId) ON DELETE CASCADE,
    --CONSTRAINT FK_Surveys_KidWantedCounts_KidsWantedCountId FOREIGN KEY (KidsWantedCountId) REFERENCES dbo.KidWantedCounts (KidWantedCountId) ON DELETE CASCADE,
    --CONSTRAINT FK_Surveys_WantedKidWantedCounts_WantedKidsWantedCountId FOREIGN KEY (WantedKidsWantedCountId) REFERENCES dbo.WantedKidWantedCounts (WantedKidWantedCountId) ON DELETE CASCADE,
    --CONSTRAINT FK_Surveys_DatePackages_DatePackageId FOREIGN KEY (DatePackageId) REFERENCES dbo.DatePackages (DatePackageId) ON DELETE CASCADE,
    --CONSTRAINT FK_Surveys_Referrers_ReferrerId FOREIGN KEY (ReferrerId) REFERENCES dbo.Referrers (ReferrerId) ON DELETE CASCADE,
    --CONSTRAINT FK_Surveys_Origins_OriginId FOREIGN KEY (OriginId) REFERENCES Origins(OriginId) 
);


CREATE NONCLUSTERED INDEX IX_WantedSurveyId
    ON dbo.Surveys(WantedSurveyId ASC);

--CREATE NONCLUSTERED INDEX IX_KidsCountId
--    ON dbo.Surveys(KidsCountId ASC);

--CREATE NONCLUSTERED INDEX IX_KidsWantedCountId
--    ON dbo.Surveys(KidsWantedCountId ASC);

--CREATE NONCLUSTERED INDEX IX_WantedKidsWantedCountId
--    ON dbo.Surveys(WantedKidsWantedCountId ASC);

--CREATE NONCLUSTERED INDEX IX_DatePackageId
--    ON dbo.Surveys(DatePackageId ASC);

--CREATE NONCLUSTERED INDEX IX_ReferrerId
--    ON dbo.Surveys(ReferrerId ASC);
*/